### ISSUE TITLE
404 Error When Using Prune Command

### ISSUE THREAD

**Issue by AriRexouium** [TheRacingLion/Discord-SelfBot#18]
```javascript
[18:39:58] Promise was rejected but there was no error handler Error
Error: 404 NOT FOUND on DELETE /channels/247946179650912256/messages/307284761695748096

{"code": 10008, "message": "Unknown Message"}
    at IncomingMessage.resp.once (C:\Users\acehe_000\Desktop\Discord-SelfBot\node_modules\eris\lib\rest\RequestHandler.js:198:39)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I've tried to fix it, but I haven't figured it out. I even did a clean install on my second computer to see if it would fix the problem, however it did not.

**Comment by TheRacingLion** [comment]
Probably some bug in the code, will try to fix it asap.

**Comment by AriRexouium** [comment]
I've actually noticed that it sometimes it clears messages, other times it doesn't.

Also, I noticed a bug similar to this when the bot tried to send a webhook message. This also can happen when it detects when someone sends a keyword.

```javascript
[20:09:54] Mention  |> Ace Servers|> #commands|> Suggestions (281041859692855296):

@Aceheliflyer, Sent you a DM with information.

[20:10:01] Promise was rejected but there was no error handler Error
Error: 400 BAD REQUEST on POST /webhooks/307669804033114123/MSxT71x45Gtf2PVmSx99m9KG4ESZV9aBDlBjEYI2HC8WIN30h2r2lo5NdBXywexqGDmm

{"embeds": ["0"]}
    at IncomingMessage.resp.once (C:\Users\acehe_000\Desktop\Discord-SelfBot\node_modules\eris\lib\rest\RequestHandler.js:198:39)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
Sometimes it spits out this error, other times it doesn't.

**Comment by TheRacingLion** [comment]
This happens when the bot tries to delete a message that has already been deleted. I think it is a bug in the new command message deletion config.

**Comment by Arzte** [comment]
hmm, I wonder if a good way to handle it would be to ignore/remove messages that begin with the command prefix in the prune array prior to deleting all non-command messages.

**Comment by Arzte** [comment]
If you change ``commands/prune.js`` on line 11 to
``.filter(m => m.content.charAt(0).indexOf(self.config.prefix) === -1)`` you can get rid of the error for now, however it prevents *any* msg that starts with - to be ignored for pruning, not just the initial command msg.

**Comment by Arzte** [comment]
#46 Fixes this error, I have tested and confirmed this on my local instance.
