### ISSUE TITLE
Error : doesn't work

### ISSUE THREAD

**Issue by MonkeyPlayzMC** [TheRacingLion/Discord-SelfBot#2]

**Comment by MonkeyPlayzMC** [comment]
C:\Users\choco\Desktop\Discord-SelfBot-master>goto START

C:\Users\choco\Desktop\Discord-SelfBot-master>node self.js
module.js:591
    throw err;
    ^

SyntaxError: C:\Users\choco\Desktop\Discord-SelfBot-master\config\config.json: Unexpected string in JSON at position 224
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:588:27)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\choco\Desktop\Discord-SelfBot-master\self.js:10:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

C:\Users\choco\Desktop\Discord-SelfBot-master>goto START

C:\Users\choco\Desktop\Discord-SelfBot-master>node self.js

**Comment by MonkeyPlayzMC** [comment]
NVM!
