### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by BroWtfIsMyUsername** [TheRacingLion/Discord-SelfBot#22]
oem@1337 ~/Desktop/Discord-SelfBot-master $ sudo node self.js 
[sudo] password for oem: 
/home/oem/Desktop/Discord-SelfBot-master/self.js:25
let isReady = false
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by BroWtfIsMyUsername** [comment]
Fix this but I'm having some kind of "warning" still and it isn't working.
https://imgur.com/a/ysLbq

**Comment by ghost** [comment]
Check that your token is correct in config/config.json , it's probably why you're getting this warning message.

**Comment by BroWtfIsMyUsername** [comment]
Issue has been fixed thanks.
