### ISSUE TITLE
Error: Request timed out

### ISSUE THREAD

**Issue by rabbit-93** [TheRacingLion/Discord-SelfBot#30]
Does your bot support http proxy? I got this error when trying to use bot:

> [10:33:40] Bot Error
Error: Request timed out (>15000ms) on GET /gateway
    at ClientRequest.<anonymous> (Discord-SelfBot\node_modules\eris\lib\rest\RequestHandler.js:256:32)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.emitTimeout (_http_client.js:679:10)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket.Socket._onTimeout (net.js:351:8)
    at ontimeout (timers.js:386:14)

**Comment by TheRacingLion** [comment]
@koperkiewicz This just means the request the bot sent to discord took longer to process than what discord was prepared to wait. So its most likely a connection issue, either on discord's end or on your end.
