### ISSUE TITLE
Throw Err Module.js:591

### ISSUE THREAD

**Issue by VSabertail** [TheRacingLion/Discord-SelfBot#33]
ted token
 in JSON at position 109
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:588:27)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>

**Comment by VSabertail** [comment]
![image](https://user-images.githubusercontent.com/17517280/27099917-6f44f820-504a-11e7-9c21-8eda5ee65c7f.png)

**Comment by TheRacingLion** [comment]
Sorry for the late reply, but there isn't enough info on this for me to be able to help you. Might have been a setup problem or just some random error. If you have more info on this feel free to re-open this issue.
