### ISSUE TITLE
Unexpected token } in JSON at position 907

### ISSUE THREAD

**Issue by calvinhg** [TheRacingLion/Discord-SelfBot#35]
So I had the bot running a while back. But I was logging a word I didn't want, and after failing to find out how to restart the bot with a command, I closed cmd and restarted it.

But now it gives me this error: 
```
module.js:590
    throw err;
    ^

SyntaxError: C:\Users\LordKarma88\AppData\Roaming\discordptb\Selfbot\TheRacingLion\config\config.json: Unexpected token } in JSON at position 907
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\LordKarma88\AppData\Roaming\discordptb\Selfbot\TheRacingLion\self.js:15:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```
Yes, I am sure the token is right: `  "token": "MjI1ODEyNDg1whatever",`

Also, there isn't any position 907 in config.json. Any idea what's wrong?

**Comment by DingleFlop** [comment]
Please provide your config.json, but, I can't stress this enough, with your TOKEN HIDDEN.

**Comment by calvinhg** [comment]
Thank you for answering, here is my config.json:
```
{
  "token": "MjI1ODEyNDg1Mzg1whatever",
  "ownerID": "225812485385486337",
  "prefix": "r.",
  "rotatePlayingGame": true,
  "rotatePlayingGameTime" : 10000,
  "rotatePlayingGameInStreamingStatus": false,
  "rotateAvatarImage": true,
  "rotateAvatarImageTime" : 600000,
  "defaultStatus": "idle",
  "mentionNotificator": {
    "inConsole": false,
    "inNotificationChannel": true,
    "logBlockedUsers": true,
    "ignoredServers": ["SERVER ID"]
  },
  "keywordNotificator": {
    "inConsole": true,
    "inNotificationChannel": true,
    "logBlockedUsers": false,
    "caseInsensitive": true,
    "ignoredServers": ["SERVER ID"]
  },
  "eventNotificator": {
    "inConsole": false,
    "inNotificationChannel": true
  },
  "notificationChannelID": "324151505752162304",
  "defaultEmbedColor": "#117ea6",
  "deleteCommandMessages": false,
  "deleteCommandMessagesTime": 
}
```

EDIT: when I had it copied I noticed there were 909 characters in the file. So I went and found the 907th character, and its the part at the way end: `"deleteCommandMessagesTime": `.
Maybe I have to add a value to that line? Although in the setup it says "if you do want the command messages deleted, this is the time the bot should wait before doing it (in milliseconds)".

**Comment by delphiactual** [comment]
```
  },
  "notificationChannelID": "324151505752162304",
  "defaultEmbedColor": "#117ea6",
  "deleteCommandMessages": false,
  "deleteCommandMessagesTime":  <<number>>
}
```

you deleted a number that is required even if it isnt being used

**Comment by calvinhg** [comment]
That's what I thought, check my edit. How can I set it to never delete? Can I even do that?

**Comment by delphiactual** [comment]
by setting the key above it to false

**Comment by calvinhg** [comment]
Oh ok thanks, I understand now.
