### ISSUE TITLE
Refusing ID

### ISSUE THREAD

**Issue by Alzter** [TheRacingLion/Discord-SelfBot#37]
{
  "token": "????????????????????????????????????????????????????????????",
  "ownerID": "331011619452878859",
  "prefix": "-",
  "rotatePlayingGame": true,
  "rotatePlayingGameTime" : 150000,
  "rotatePlayingGameInStreamingStatus": false,
  "rotateAvatarImage": true,
  "rotateAvatarImageTime" : 600000,
  "defaultStatus": "idle",
  "mentionNotificator": {
    "inConsole": true,
    "inNotificationChannel": true,
    "logBlockedUsers": false,
    "ignoredServers": ["SERVER ID"]
  },
  "keywordNotificator": {
    "inConsole": true,
    "inNotificationChannel": true,
    "logBlockedUsers": false,
    "caseInsensitive": true,
    "ignoredServers": ["SERVER ID"]
  },
  "eventNotificator": {
    "inConsole": true,
    "inNotificationChannel": false
  },
  "notificationChannelID": "Notification channel ID if you set 'inNotificationChannel' to true at least once",
  "defaultEmbedColor": "#117ea6",
  "deleteCommandMessages": true,
  "deleteCommandMessagesTime": 15000
}

results in:

SyntaxError: /Users/Alzter/Desktop/Discord-SelfBot-master/config/games.json: Unexpected token 
 in JSON at position 91
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:588:27)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Alzter/Desktop/Discord-SelfBot-master/self.js:16:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Discord_Selfbot@2.1.2 start: `node self.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Discord_Selfbot@2.1.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Alzter/.npm/_logs/2017-07-05T06_10_27_070Z-debug.log

(Each character of the token is replaced with question marks)

Fix this.

**Comment by DingleFlop** [comment]
Say please.

I suggest the developer ignore this until OP first apologizes, and then shows data relevant to the issue.

Such data might include where you are getting your ID from, and screenshots showing you doing so.

The dev of this not is not paid, and you should feel ashamed for acting so entitled after receiving this for free. If you want it fixed so bad, fork it and learn to code for yourself.

**Comment by DingleFlop** [comment]
As for the issue, @TheRacingLion, the JSON is well and good as checked using LINT. I bet redownloading would fix his issue.

**Comment by Alzter** [comment]
I apologize for being so rude. I will try redownloading

**Comment by DingleFlop** [comment]
@Alzter Any luck?

**Comment by TheRacingLion** [comment]
I have been a bit busy lately, so sorry for taking so long to reply to this, but @DingleFlop ty for checking the file and helping him out. @Alzter And for the "not so right" way of making the issue, its all good man. Let us know in here if you were able to get it up and going, or you still having problems.

**Comment by TheRacingLion** [comment]
Closing due to inactivity. Feel free to re-open if issue still exists.
