### ISSUE TITLE
I get the clock error a lot but I'm not sure if I can fix it

### ISSUE THREAD

**Issue by calvinhg** [TheRacingLion/Discord-SelfBot#41]
I keep on getting this error:
```
[21:54:07] Bot Error
Error: Your clock is 5554ms behind Discord's server clock. Please check your connection and system time.
    at ClientRequest.req.once (C:\Users\LordKarma88\AppData\Roaming\discordptb\Selfbot\TheRacingLion\node_modules\eris\lib\rest\RequestHandler.js:166:56)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```
The problem is, I'm not too sure how to fix that. I know that computer clocks aren't very precise, and they don't check with the world time very often, and thus it makes sense to me that my system clock is a bit off. 
Does anybody have a way to fix it, and if not, is there anyway I can prevent that error from flooding my log?

**Comment by TheRacingLion** [comment]
@Lordkarma88 Not really a selfbot problem, but I would try to update your computer data/time settings in the control panel. I would just maybe google the issue and see if there are any other fixes.
Maybe refer to something like [this](https://www.tekrevue.com/tip/fix-incorrect-windows-clock/).
