### ISSUE TITLE
400 Bad request when using mention stalker

### ISSUE THREAD

**Issue by Catbirby** [TheRacingLion/Discord-SelfBot#52]
(removed webhook token) I receive this error when being mentioned or have a keyword mentioned

[16:08:10] Promise was rejected but there was no error handler Error
Error: 400 BAD REQUEST on POST `/webhooks/301921879885873153/0b_f5u0

{"embeds": ["0"]}
    at IncomingMessage._respStream.on.once (C:\Users\ellis\Documents\Discord\Discord-SelfBot\node_modules\eris\lib\rest\RequestHandler.js:232:39)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

[16:08:10] Promise was rejected but there was no error handler Error
Error: 400 BAD REQUEST on POST /webhooks/301921879885873153/0b7QpnD06MVqc

{"embeds": ["0"]}
    at IncomingMessage._respStream.on.once (C:\Users\ellis\Documents\Discord\Discord-SelfBot\node_modules\eris\lib\rest\RequestHandler.js:232:39)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by TheRacingLion** [comment]
@LunarSkies Was this working fine for you before? If yes, what changed between the time you last used it and now? And it happens on every mention and keyword notification, or only a few?

**Comment by washingdone** [comment]
I've only had this problem start recently, but it seems to happen randomly. It may be another issue with discord's API and not anything to do with the bot itself.

**Comment by sn8to** [comment]
Could you post the entire link, please? The /webhooks one.
(Warning: This Webhook link can be used to access that webhook and post messages in the server it was created in. I'm only using it to see if the webhook exists and is working correctly as it should.)
