### ISSUE TITLE
Mention logging

### ISSUE THREAD

**Issue by Catbirby** [TheRacingLion/Discord-SelfBot#6]
I run into this anytime someone mentions me, it doesn't log to a channel
```[21:08:07] Bot Error  
TypeError: Cannot read property 'id' of undefined
    at CommandClient.self.on (/Users/ellistonjames/Documents/bots/Discord-SelfBot/utils/mentionStalker.js:12:88)
    at emitOne (events.js:101:20)
    at CommandClient.emit (events.js:188:7)
    at Shard.wsEvent (/Users/ellistonjames/Documents/bots/Discord-SelfBot/node_modules/eris/lib/gateway/Shard.js:394:33)
    at WebSocket.ws.onmessage (/Users/ellistonjames/Documents/bots/Discord-SelfBot/node_modules/eris/lib/gateway/Shard.js:1425:34)
    at WebSocket.onMessage (/Users/ellistonjames/Documents/bots/Discord-SelfBot/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/ellistonjames/Documents/bots/Discord-SelfBot/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/ellistonjames/Documents/bots/Discord-SelfBot/node_modules/ws/lib/Receiver.js:536:18```

**Comment by TheRacingLion** [comment]
Will look into it and push a fix asap 👍

**Comment by TheRacingLion** [comment]
Fixed in ["**fix mention logging**"](https://github.com/TheRacingLion/Discord-SelfBot/commit/3adebea7f4aafa21dd687059e5678ecc280da35a). Thanks.
