### ISSUE TITLE
Run.bat isnt loading up correctly.

### ISSUE THREAD

**Issue by bigtomatos** [TheRacingLion/Discord-SelfBot#60]
when i load it it just spits out this: 
SyntaxError: C:\Users\john\Desktop\Discord-SelfBot-master\config\paste.json: Unexpected token ] in JSON at position 1434
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:643:27)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\john\Desktop\Discord-SelfBot-master\commands\paste.js:6:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)

**Comment by Fifkee** [comment]
Try redownloading Paste.json and moving it into the config folder, and click replace after you do.

**Comment by AriRexouium** [comment]
If you made changes to your `paste.json` file, make sure it's formated correctly.
