### ISSUE TITLE
Bot cannot find eris.

### ISSUE THREAD

**Issue by sauceysaucer** [TheRacingLion/Discord-SelfBot#61]
Upon launching the bot, I get this error over and over again, not sure how to fix it.

Error: Cannot find module 'eris'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Files\Servers\Discord bots\SELFBOT\TheRacingLion\Discord-SelfBot\self.js:7:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

**Comment by AriRexouium** [comment]
Did you run `installer.bat`?

**Comment by sauceysaucer** [comment]
Indeed

**Comment by jtsshieh** [comment]
Go to the command line, type in `npm install eris --save`
