### ISSUE TITLE
Bot does not start

### ISSUE THREAD

**Issue by nullobsi** [TheRacingLion/Discord-SelfBot#66]
It doesn't start, when i try to strat it , it says:
`module.js:515
    throw err;
    ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jp/repos/Discord-SelfBot/src/utils/ConfigValidator.js:7:16)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)`

**Comment by AriRexouium** [comment]
Reinstall the bot or run `npm i moment --save` in terminal in the root directory of your bot.
