### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by cynaax** [TheRacingLion/Discord-SelfBot#73]
SyntaxError: C:\Users\agt20\Discord-SelfBot\config\config.json: Unexpected token M in JSON at position 16
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:679:27)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\agt20\Discord-SelfBot\self.js:15:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)

**Comment by TechGamer21** [comment]
Sorry if I didn't explain anything too much in it, basically when I run "Start.bat" it shows that error, I have looked through the "config.json" file and nothing seems to be wrong with what I'm seeing
